<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>islemap-thienvyma-telemetry</AssemblyName>
    <RootNamespace>IslemapThienvyma.Telemetry</RootNamespace>
    <AssemblyTitle>islemap-thienvyma realtime telemetry</AssemblyTitle>
    <Product>islemap-thienvyma</Product>
    <Authors>thienvyma</Authors>
    <Company>thienvyma</Company>
    <Copyright>Copyright © 2026 thienvyma</Copyright>
    <Version>2.4.8</Version>
    <FileVersion>2.4.8.0</FileVersion>
    <AssemblyVersion>2.4.8.0</AssemblyVersion>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SharpPcap" Version="6.3.1" />
    <PackageReference Include="PacketDotNet" Version="1.4.8" />
  </ItemGroup>
</Project>
